version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network 

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rookworst31!
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: Rookworst31!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network 

volumes:
  mysql_data:

networks:
  my-network:
